# Generated by Django 5.0.6 on 2025-07-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='des',
            new_name='desc',
        ),
    ]
