# Generated by Django 5.0.6 on 2025-07-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_des_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='des',
        ),
    ]
